# Generated by Django 3.2.12 on 2024-02-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0002_alter_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=250),
        ),
    ]
