# Generated by Django 3.2.12 on 2024-02-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
