# Generated by Django 3.2.12 on 2024-03-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0008_auto_20240302_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/apl')),
            ],
        ),
    ]
