# Generated by Django 3.2.12 on 2024-03-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/tutor'),
        ),
    ]
