# Generated by Django 3.2.12 on 2024-03-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='publication_date',
            new_name='date',
        ),
    ]
