# Generated by Django 5.0.3 on 2024-04-23 19:43

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_comm_tut_text_alter_tutor_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
