# Generated by Django 3.2.12 on 2024-03-11 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0003_auto_20240311_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='Tutor',
        ),
    ]
