# Generated by Django 3.2.12 on 2024-03-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_rename_publication_date_tutor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comm_tut',
            name='text',
            field=models.TextField(),
        ),
    ]
