# Generated by Django 5.0.3 on 2024-03-12 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0002_myuser'),
        ('tutor', '0004_rename_tutorial_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='author',
            field=models.ForeignKey(default='yury', on_delete=django.db.models.deletion.CASCADE, to='reglog.myuser'),
        ),
    ]
