# Generated by Django 5.0.3 on 2024-04-25 16:03

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_comm_tut_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='image',
        ),
        migrations.AddField(
            model_name='tutor',
            name='public_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comm_tut',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='text'),
        ),
    ]
