# Generated by Django 3.2.12 on 2024-03-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_comm_tut_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='text',
            field=models.TextField(),
        ),
    ]
