# Generated by Django 3.2.12 on 2024-03-08 13:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_alter_tutor_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
