# Generated by Django 5.0.3 on 2024-05-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_remove_tutor_image_tutor_public_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='cost_rating',
            field=models.IntegerField(default=5),
        ),
    ]
