# Generated by Django 5.0.3 on 2024-05-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
