# Generated by Django 3.2.12 on 2024-03-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0002_auto_20240306_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='firstname',
        ),
    ]
