# Generated by Django 3.2.12 on 2024-03-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0003_rename_username_user_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
