# Generated by Django 3.2.12 on 2024-03-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0004_auto_20240306_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='about',
        ),
    ]
