# Generated by Django 5.0.3 on 2024-05-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AlterField(
            model_name='forum_question',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='forum_question',
            name='cat_topic',
            field=models.ManyToManyField(to='forum.cat_topics'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
