# Generated by Django 5.0.3 on 2024-04-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_vote_answer_remove_vote_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='forum_question',
            name='cat_topic',
            field=models.ManyToManyField(to='forum.cat_topics'),
        ),
    ]
