# Generated by Django 5.0.3 on 2024-04-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_comment_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_answer',
            old_name='post',
            new_name='post_comment',
        ),
    ]
