# Generated by Django 5.0.3 on 2024-04-30 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_rename_post_comment_answer_post_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_answer',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'Up Vote'), (-1, 'Down Vote')], default=1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum_answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'answer')},
            },
        ),
        migrations.AddField(
            model_name='forum_answer',
            name='votes',
            field=models.ManyToManyField(related_name='voted_answers', through='forum.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comment_Answer',
        ),
    ]
