# Generated by Django 5.0.3 on 2024-04-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_forum_answer_vote_count_vote_forum_answer_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum_answer',
            name='votes',
        ),
        migrations.RenameField(
            model_name='forum_answer',
            old_name='vote_count',
            new_name='rating',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
