# Generated by Django 3.2.12 on 2024-03-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='static/images/newart'),
        ),
    ]
