# Generated by Django 3.2.12 on 2024-03-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newart', '0005_news_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
