# Generated by Django 4.1.7 on 2024-05-16 22:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
