# Generated by Django 4.1.7 on 2024-05-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0002_alter_answer_name_alter_question_q_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cost_rating',
            field=models.IntegerField(default=2),
        ),
    ]
